# Generated by Django 4.1.7 on 2023-02-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_activation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
    ]
