# Generated by Django 4.1.7 on 2023-03-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('female', 'female')], max_length=300)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
