# Generated by Django 4.1.7 on 2023-02-16 21:45

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_logo_category),
        ),
    ]
